// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD03FjGvTVdiQg3T-3cE6Q6hEAboK4Apjg',
    appId: '1:710371668614:web:fddbc9499730c125add707',
    messagingSenderId: '710371668614',
    projectId: 'beijing-metro-offline-map',
    authDomain: 'beijing-metro-offline-map.firebaseapp.com',
    storageBucket: 'beijing-metro-offline-map.appspot.com',
    measurementId: 'G-GVF5W2Y7HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ92Lzv_DGfZ7Vj7Y-OiKZi8BdH4Ex_VI',
    appId: '1:710371668614:android:7ea6bff9a7662fd6add707',
    messagingSenderId: '710371668614',
    projectId: 'beijing-metro-offline-map',
    storageBucket: 'beijing-metro-offline-map.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_JjmtNvqhp9fvV3N1FTg5PHqfCph_Ces',
    appId: '1:710371668614:ios:9fedb3fb870f2f08add707',
    messagingSenderId: '710371668614',
    projectId: 'beijing-metro-offline-map',
    storageBucket: 'beijing-metro-offline-map.appspot.com',
    iosBundleId: 'com.example.beijingSubway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_JjmtNvqhp9fvV3N1FTg5PHqfCph_Ces',
    appId: '1:710371668614:ios:9fedb3fb870f2f08add707',
    messagingSenderId: '710371668614',
    projectId: 'beijing-metro-offline-map',
    storageBucket: 'beijing-metro-offline-map.appspot.com',
    iosBundleId: 'com.example.beijingSubway',
  );
}
