import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  Map<String, Map<String, String>> get keys => {
  "Chinese": {
    "text1": "世界离线",
    "text2": "地铁",
    "sidebartext1": "地铁地图",
    "sidebartext2": "事件",
    "sidebartext3": "要做的事",
    "sidebartext4": "酒店",
    "Selectcity": "选择城市",
    "button1": "离线地铁图",
    "Heading1": "要做的事",
    "Heading2": "酒店",
    "PrivatePolicy": "隐私政策",
    "flag": "https://flagcdn.com/cn.svg"
  },
  "Korean": {
    "text1": "세계 오프라인",
    "text2": "지하철",
    "sidebartext1": "지하철 지도",
    "sidebartext2": "이벤트",
    "sidebartext3": "할 일",
    "sidebartext4": "호텔",
    "Selectcity": "도시 선택",
    "button1": "오프라인 지하철 맵",
    "Heading1": "할 일",
    "Heading2": "호텔",
    "PrivatePolicy": "개인 정보 정책",
    "flag": "https://flagcdn.com/kr.svg"
  },
  "Arabic": {
    "text1": "العالم دون اتصال",
    "text2": "مترو",
    "sidebartext1": "خريطة المترو",
    "sidebartext2": "الأحداث",
    "sidebartext3": "الأشياء للقيام بها",
    "sidebartext4": "الفنادق",
    "Selectcity": "اختر المدينة",
    "button1": "خريطة المترو دون اتصال",
    "Heading1": "الأشياء للقيام بها",
    "Heading2": "الفنادق",
    "PrivatePolicy": "سياسة خاصة",
    "flag": "https://flagcdn.com/sa.svg"
  },
  "Spanish": {
    "text1": "Mundo sin conexión",
    "text2": "Metro",
    "sidebartext1": "Mapa del metro",
    "sidebartext2": "Eventos",
    "sidebartext3": "Cosas para hacer",
    "sidebartext4": "Hoteles",
    "Selectcity": "Seleccionar ciudad",
    "button1": "Mapa del metro sin conexión",
    "Heading1": "Cosas para hacer",
    "Heading2": "Hoteles",
    "PrivatePolicy": "Política de privacidad",
    "flag": "https://flagcdn.com/es.svg"
  },
  "Urdu": {
    "text1": "دنیا آف لائن",
    "text2": "میٹرو",
    "sidebartext1": "میٹرو کا نقشہ",
    "sidebartext2": "واقعات",
    "sidebartext3": "کرنے کے لئے چیزیں",
    "sidebartext4": "ہوٹل",
    "Selectcity": "شہر منتخب کریں",
    "button1": "آف لائن میٹرو نقشہ",
    "Heading1": "کرنے کے لئے چیزیں",
    "Heading2": "ہوٹل",
    "PrivatePolicy": "پرائیویسی پالیسی",
    "flag": "https://flagcdn.com/pk.svg"
  },
  "Hindi": {
    "text1": "विश्व ऑफ़लाइन",
    "text2": "मेट्रो",
    "sidebartext1": "मेट्रो मानचित्र",
    "sidebartext2": "घटनाएँ",
    "sidebartext3": "करने के लिए चीजें",
    "sidebartext4": "होटल",
    "Selectcity": "शहर चुनें",
    "button1": "ऑफ़लाइन मेट्रो मानचित्र",
    "Heading1": "करने के लिए चीजें",
    "Heading2": "होटल",
    "PrivatePolicy": "निजता नीति",
    "flag": "https://flagcdn.com/in.svg"
  },
  "Bengali": {
    "text1": "বিশ্ব অফলাইন",
    "text2": "মেট্রো",
    "sidebartext1": "মেট্রো ম্যাপ",
    "sidebartext2": "ইভেন্ট",
    "sidebartext3": "করার জন্য জিনিসপত্র",
    "sidebartext4": "হোটেল",
    "Selectcity": "শহর নির্বাচন করুন",
    "button1": "অফলাইন মেট্রো ম্যাপ",
    "Heading1": "করার জন্য জিনিসপত্র",
    "Heading2": "হোটেল",
    "PrivatePolicy": "গোপনীয়তা নীতি",
    "flag": "https://flagcdn.com/bd.svg"
  },
  "Turkish": {
    "text1": "Dünya Çevrimdışı",
    "text2": "Metro",
    "sidebartext1": "Metro Haritası",
    "sidebartext2": "Etkinlikler",
    "sidebartext3": "Yapılacak Şeyler",
    "sidebartext4": "Oteller",
    "Selectcity": "Şehir Seç",
    "button1": "Çevrimdışı Metro Haritası",
    "Heading1": "Yapılacak Şeyler",
    "Heading2": "Oteller",
    "PrivatePolicy": "Gizlilik Politikası",
    "flag": "https://flagcdn.com/tr.svg"
  },
  "Russian": {
    "text1": "Мир офлайн",
    "text2": "Метро",
    "sidebartext1": "Карта метро",
    "sidebartext2": "События",
    "sidebartext3": "Дела",
    "sidebartext4": "Отели",
    "Selectcity": "Выберите город",
    "button1": "Офлайн карта метро",
    "Heading1": "Дела",
    "Heading2": "Отели",
    "PrivatePolicy": "Политика конфиденциальности",
    "flag": "https://flagcdn.com/ru.svg"
  },
  "English": {
    "text1": "World Offline",
    "text2": "Metro",
    "sidebartext1": "Metro Map",
    "sidebartext2": "Events",
    "sidebartext3": "Things to do",
    "sidebartext4": "Hotels",
    "Selectcity": "Select City",
    "button1": "Offline Metro Map",
    "Heading1": "Things To Do",
    "Heading2": "Hotels",
    "PrivatePolicy": "Privacy Policy",
    "flag": "https://flagcdn.com/us.svg"
  }
};}
