// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzKCTo5fWGRv4SaVi0Du0fGlQmULg7IhY',
    appId: '1:134635494144:web:fa9d79549dacb5cc92b1e5',
    messagingSenderId: '134635494144',
    projectId: 'new-york-subway-map',
    authDomain: 'new-york-subway-map.firebaseapp.com',
    storageBucket: 'new-york-subway-map.appspot.com',
    measurementId: 'G-RS5EVZB066',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZA-y8QYHwRs8F1fVNxxsA37m3VtH0riY',
    appId: '1:134635494144:android:c8d374ea5f65e0c892b1e5',
    messagingSenderId: '134635494144',
    projectId: 'new-york-subway-map',
    storageBucket: 'new-york-subway-map.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJAbAGeSpk6dABGjwLnu7Rlm06OBSHIIw',
    appId: '1:134635494144:ios:1a1769ef17d3a00492b1e5',
    messagingSenderId: '134635494144',
    projectId: 'new-york-subway-map',
    storageBucket: 'new-york-subway-map.appspot.com',
    iosBundleId: 'com.example.newYork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJAbAGeSpk6dABGjwLnu7Rlm06OBSHIIw',
    appId: '1:134635494144:ios:1a1769ef17d3a00492b1e5',
    messagingSenderId: '134635494144',
    projectId: 'new-york-subway-map',
    storageBucket: 'new-york-subway-map.appspot.com',
    iosBundleId: 'com.example.newYork',
  );
}
