// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8RYRmvFGQU8TGGU-rWrXpVQkFM3lp6-U',
    appId: '1:327401740887:web:89398665573ff52886e112',
    messagingSenderId: '327401740887',
    projectId: 'guangzhou-metro-offline-map',
    authDomain: 'guangzhou-metro-offline-map.firebaseapp.com',
    storageBucket: 'guangzhou-metro-offline-map.appspot.com',
    measurementId: 'G-3Y98E79H0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLGiewLDQzLiUzqQ6A0sne4RXuC0LlHYs',
    appId: '1:327401740887:android:50b2c304c37263de86e112',
    messagingSenderId: '327401740887',
    projectId: 'guangzhou-metro-offline-map',
    storageBucket: 'guangzhou-metro-offline-map.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ016c41B8-GvhKFkLEDYOkgl_sOilY8I',
    appId: '1:327401740887:ios:995a1a744b1c593286e112',
    messagingSenderId: '327401740887',
    projectId: 'guangzhou-metro-offline-map',
    storageBucket: 'guangzhou-metro-offline-map.appspot.com',
    iosBundleId: 'com.example.guangzhouMetro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ016c41B8-GvhKFkLEDYOkgl_sOilY8I',
    appId: '1:327401740887:ios:995a1a744b1c593286e112',
    messagingSenderId: '327401740887',
    projectId: 'guangzhou-metro-offline-map',
    storageBucket: 'guangzhou-metro-offline-map.appspot.com',
    iosBundleId: 'com.example.guangzhouMetro',
  );
}
