// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9GzRct3RSRnsaKcKMk-JpTwBGFVn17To',
    appId: '1:391977199004:web:e525b11eb84c041d59d459',
    messagingSenderId: '391977199004',
    projectId: 'bangkok-metro-map',
    authDomain: 'bangkok-metro-map.firebaseapp.com',
    storageBucket: 'bangkok-metro-map.appspot.com',
    measurementId: 'G-G53R2Y5CLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwivit-aX9YwgZ-ZqGm0_mqXmQ15XO01I',
    appId: '1:391977199004:android:1fb3dcc637c5e51059d459',
    messagingSenderId: '391977199004',
    projectId: 'bangkok-metro-map',
    storageBucket: 'bangkok-metro-map.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMfYS0s-bjLD3sg6iTzDOWu5KEk4B1ixY',
    appId: '1:391977199004:ios:39e32eebdf48182b59d459',
    messagingSenderId: '391977199004',
    projectId: 'bangkok-metro-map',
    storageBucket: 'bangkok-metro-map.appspot.com',
    iosBundleId: 'com.example.bangkokMetro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMfYS0s-bjLD3sg6iTzDOWu5KEk4B1ixY',
    appId: '1:391977199004:ios:39e32eebdf48182b59d459',
    messagingSenderId: '391977199004',
    projectId: 'bangkok-metro-map',
    storageBucket: 'bangkok-metro-map.appspot.com',
    iosBundleId: 'com.example.bangkokMetro',
  );
}
