import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  Map<String, Map<String, String>> get keys => {
        "English": {
          "text1": "Let's Explore",
          "text2": "London",
          "sidebartext1": "Metro Map",
          "sidebartext2": "Events",
          "sidebartext3": "Things to do",
          "sidebartext4": "Hotels",
          "sidebartext5": "Weather",
          "sidebartext6": "About",
          "sidebartext7": "Contact Us",
          "sidebartext8": "Instagram",
          "sidebartext9": "Facebook",
          "button1": "Metro Map",
          "ContactText":
              "Contact us at a convenient time for you and we will answer all your questions.",
          "ContactTile1": "Write to us",
          "Heading1": "Things To Do",
          "Heading2": "Hotels",
          "Heading3": "Weather",
          "Heading4": "About Us",
          "Heading5": "Contact Us",
          "Publish": "Publisher's note",
          "PublishText":
              '''This app has been written and designed to provide thorough information about this place. As with the publication of the application, I do not ignore the application's limitations. At times, it will be necessary to do more research on the place.

I recommend that the reader peruse and reflect upon these pages without prejudice. This application has been offered for sale and onward transmission through whatever means deemed appropriate by the author Who Will not be engaged in rendering financial, legal — and travel guidance or any other kind of service provided in the city. In any case that may arise where professional travel guide is required, then the services of a professional in this field should be enlisted.

All rights reserved. NO PART of this application can be reproduced in whatever format without the express written authority of the author.

Every single picture is used under license from Shutterstock.com If you would like specific information about a picture, please get in touch with us. None of the pictures can be reproduced or used under any circumstances besides what is intended by this app.

All rights reserved. -No part of this application may be reproduced in any form or by any electronic or mechanical means, including information storage and retrieval systems; without permission in writing from the Author/Publisher.''',
          "PrivatePolicy": "Privacy Policy",
        },
        "Korean": {
          "text1": "탐험합시다",
          "text2": "런던",
          "sidebartext1": "지하철 지도",
          "sidebartext2": "이벤트",
          "sidebartext3": "할 일",
          "sidebartext4": "호텔",
          "sidebartext5": "날씨",
          "sidebartext6": "소개",
          "sidebartext7": "문의하기",
          "sidebartext8": "인스타그램",
          "sidebartext9": "페이스북",
          "button1": "오프라인 지하철 지도",
          "ContactText": "편리한 시간에 저희에게 연락해 주시면 모든 질문에 답변해 드리겠습니다.",
          "ContactTile1": "우리에게 쓰기",
          "Heading1": "할 일",
          "Heading2": "호텔",
          "Heading3": "날씨",
          "Heading4": "우리에 대하여",
          "Heading5": "문의하기",
          "Publish": "출판사의 노트",
          "PublishText":
              "이 앱은이 장소에 대한 철저한 정보를 제공하기 위해 작성 및 디자인되었습니다. 애플리케이션의 게시와 함께 저자가 앱의 제한을 무시하지 않습니다. 때로는 장소에 대해 더 많은 연구가 필요할 수 있습니다.\n독자는 편견 없이 이 페이지를 읽고 숙고하는 것을 권장합니다. 이 애플리케이션은 저자가 적절하다고 판단하는 수단을 통해 판매 및 전송을 위해 제공되었습니다. 이 도시에서 제공되는 금융, 법률 및 여행 안내 또는 이와 유사한 서비스를 제공하지 않을 것입니다. 전문 여행 가이드가 필요한 경우 해당 분야의 전문가의 서비스를 이용해야 합니다.\n모든 권리 보유. 이 애플리케이션의 어느 부분도 저자의 명시적 서면 승인 없이 어떤 형태로든 복제될 수 없습니다.\n모든 사진은 Shutterstock.com의 라이선스에 따라 사용되었습니다. 특정 사진에 대한 자세한 정보가 필요한 경우 저희에게 연락하십시오. 이 앱에서 의도된 것 이외의 상황에서는 어떤 경우에도 사진을 재생산하거나 사용할 수 없습니다.\n모든 권리 보유. -저자 / 출판사로부터 서면 허가없이 정보 저장 및 검색 시스템을 포함한 모든 형태 또는 전자 또는 기계적 수단으로 이 애플리케이션의 어떤 부분도 재생산될 수 없습니다.",
          "PrivatePolicy": "개인정보 보호정책",
        },
        "Chinese": {
          "text1": "让我们探索",
          "text2": "伦敦",
          "sidebartext1": "地铁地图",
          "sidebartext2": "活动",
          "sidebartext3": "事情要做",
          "sidebartext4": "酒店",
          "sidebartext5": "天气",
          "sidebartext6": "关于",
          "sidebartext7": "联系我们",
          "sidebartext8": "Instagram",
          "sidebartext9": "脸书",
          "ContactText": "在方便的时候联系我们，我们会回答您的所有问题。",
          "ContactTile1": "写信给我们",
          "Heading1": "要做的事",
          "Heading2": "酒店",
          "Heading3": "天气",
          "Heading4": "关于我们",
          "Heading5": "联系我们",
          "Publish": "出版商的注意",
          "PublishText":
              "该应用程序已经编写和设计，以提供有关该地方的详细信息。随着应用程序的发布，我不会忽视应用程序的限制。有时需要对该地方进行更多的研究。\n我建议读者无偏见地阅读和思考这些页面。此应用程序已通过作者认为适当的任何手段出售和转发。在任何需要专业旅行指南的情况下，应聘请该领域的专业人士的服务。\n版权所有。未经作者书面许可，本应用程序的任何部分均不得以任何形式复制。\n所有图片均根据Shutterstock.com的许可证使用。如果您需要有关图片的特定信息，请与我们联系。除本应用程序所用之外，任何情况下都不能复制或使用任何图片。\n保留所有权利。-未经作者/出版商书面许可，任何形式或任何电子或机械手段，包括信息存储和检索系统，都不得重现本应用程序的任何部分。",
          "PrivatePolicy": "隐私政策"
        },
        "Arabic": {
          "text1": "لنستكشف",
          "text2": "لندن",
          "sidebartext1": "خريطة المترو",
          "sidebartext2": "الأحداث",
          "sidebartext3": "الأشياء التي يجب القيام بها",
          "sidebartext4": "الفنادق",
          "sidebartext5": "الطقس",
          "sidebartext6": "حول",
          "sidebartext7": "اتصل بنا",
          "sidebartext8": "انستغرام",
          "sidebartext9": "الفيسبوك",
          "button1": "خريطة المترو غير متصلة",
          "ContactText": "اتصل بنا في الوقت المناسب لك وسنجيب على جميع أسئلتك.",
          "ContactTile1": "اكتب لنا",
          "Heading1": "الأشياء التي يجب القيام بها",
          "Heading2": "الفنادق",
          "Heading3": "الطقس",
          "Heading4": "معلومات عنا",
          "Heading5": "اتصل بنا",
          "Publish": "ملاحظة الناشر",
          "PublishText":
              "تمت كتابة هذا التطبيق وتصميمه لتوفير معلومات شاملة حول هذا المكان. كما هو الحال مع نشر التطبيق، لا أتجاهل قيود التطبيق. في بعض الأحيان، قد يكون من الضروري القيام بمزيد من البحوث حول المكان.\nأنصح القارئ بالاطلاع على هذه الصفحات والتفكير فيها بدون تحيز. تم عرض هذا التطبيق للبيع والنقل عبر أي وسيلة تراها مناسبة من قبل الكاتب الذي لن يشارك في تقديم الإرشادات المالية أو القانونية أو السفرية أو أي نوع آخر من الخدمات المقدمة في المدينة. في أي حالة قد تنشأ فيها الحاجة إلى دليل سفر محترف، يجب استخدام خدمات محترف في هذا المجال.\nجميع الحقوق محفوظة. لا يمكن إعادة إنتاج أي جزء من هذا التطبيق بأي شكل من الأشكال دون الحصول على إذن خطي صريح من الكاتب.\nتم استخدام كل صورة تحت ترخيص من Shutterstock.com إذا كنت ترغب في الحصول على معلومات محددة حول صورة ما، يرجى الاتصال بنا. لا يمكن إعادة إنتاج أو استخدام أي من الصور تحت أي ظرف من الظروف إلا ما هو المقصود بهذا التطبيق.\nجميع الحقوق محفوظة. -لا يجوز إعادة إنتاج أي جزء من هذا التطبيق بأي شكل من الأشكال أو بأي وسيلة إلكترونية أو ميكانيكية، بما في ذلك أنظمة تخزين واسترجاع المعلومات؛ دون إذن خطي من الكاتب / الناشر.",
          "PrivatePolicy": "سياسة الخصوصية"
        },
        "Urdu": {
          "text1": "ہم اس کا تجزیہ کریں",
          "text2": "لندن",
          "sidebartext1": "میٹرو نقشہ",
          "sidebartext2": "واقعات",
          "sidebartext3": "کام کرنے کی چیزیں",
          "sidebartext4": "ہوٹل",
          "sidebartext5": "موسم",
          "sidebartext6": "کے بارے میں",
          "sidebartext7": "ہم سے رابطہ کریں",
          "sidebartext8": "انسٹاگرام",
          "sidebartext9": "فیس بک",
          "button1": "غیر متصل میٹرو نقشہ",
          "ContactText":
              "آپ کے لئے مناسب وقت پر ہم سے رابطہ کریں اور ہم آپ کے تمام سوالات کے جوابات دیں گے۔",
          "ContactTile1": "ہمیں لکھیں",
          "Heading1": "کام کرنے کی چیزیں",
          "Heading2": "ہوٹل",
          "Heading3": "موسم",
          "Heading4": "ہمارے بارے میں",
          "Heading5": "رابطہ کریں",
          "Publish": "ناشر کی نوٹ",
          "PublishText":
              "اس ایپ کو لکھا اور ڈیزائن کیا گیا ہے تاکہ اس جگہ کے بارے میں مکمل معلومات فراہم کی جا سکے۔ اس تطبیق کی شائعات کے ساتھ، میں تطبیق کی پابندیوں کو نظرانداز نہیں کرتا۔ کبھی کبھار، جگہ کے بارے میں زیادہ تحقیق کرنا ضروری ہوگا۔\nمیں قارئین سے توصیہ کرتا ہوں کہ ان صفحات کو کسی بغیر تعصب کے مطالعہ اور ان پر غور کریں۔ یہ ایپ فروخت کے لیے پیش کی گئی ہے اور مصنوعی کی طرف سے کسی بھی مواصلات کے ذریعہ کے ذریعہ۔ جو مالی، قانونی — اور سفری رہنمائی یا شہر میں فراہم کردہ کسی بھی دوسری قسم کی خدمتوں کو فراہم نہیں کرے گا۔ جہاں کبھی بھی پیش آسکتا ہے کہ پیشہ ور سفری رہنما درکار ہو، تو اس شعبے میں ایک پیشہ ور کی خدمات کو انتخاب کیا جائے۔\nتمام حقوق محفوظ ہیں۔ اس ایپ کا کوئی حصہ بھی اگر لکھے مصری اخراج کے بغیر کسی بھی فارمیٹ میں نقل اختیار کرنا ممکن نہیں ہے۔\nہر ایک تصویر کو شٹر اسٹاک.کام کی لائسنس کے تحت استعمال کیا گیا ہے اگر آپ کو کسی تصویر کے بارے میں مخصوص معلومات چاہیں تو براہ کرم ہم سے رابطہ کریں۔ کسی بھی صورت میں تصاویر کا نقل نہیں کیا جاسکتا ہے یا اس ایپ کے ذریعہ مقصود کردہ ماقع کے علاوہ استعمال کیا جاسکتا ہے۔\nتمام حقوق محفوظ ہیں۔ -کسی بھی فارم یا کسی بھی الیکٹرانک یا میکانیکل ذریعہ کے ذریعہ اس ایپ کا کوئی حصہ نقل کرایا جاسکتا ہے؛ تو شاعر / پبلشر کی طرف سے لکھی گئی اجازت کے بغیر۔",
          "PrivatePolicy": "رازداری پالیسی"
        },
        "Hindi": {
          "text1": "आइए खोजते हैं",
          "text2": "लंदन",
          "sidebartext1": "मेट्रो मानचित्र",
          "sidebartext2": "घटनाएँ",
          "sidebartext3": "करने के लिए चीजें",
          "sidebartext4": "होटल",
          "sidebartext5": "मौसम",
          "sidebartext6": "के बारे में",
          "sidebartext7": "हमसे संपर्क करें",
          "sidebartext8": "इंस्टाग्राम",
          "sidebartext9": "फेसबुक",
          "button1": "ऑफ़लाइन मेट्रो मानचित्र",
          "ContactText":
              "अपने लिए सुविधाजनक समय पर हमसे संपर्क करें और हम आपके सभी प्रश्नों का उत्तर देंगे।",
          "ContactTile1": "हमें लिखें",
          "Heading1": "करने के लिए चीजें",
          "Heading2": "होटल",
          "Heading3": "मौसम",
          "Heading4": "हमारे बारे में",
          "Heading5": "हमसे संपर्क करें",
          "Publish": "प्रकाशक का नोट",
          "PublishText":
              "यह एप्लिकेशन इस जगह के बारे में विस्तृत जानकारी प्रदान करने के लिए लिखा और डिज़ाइन किया गया है। एप्लिकेशन के प्रकाशन के साथ, मैं एप्लिकेशन की सीमाओं को नज़रअंदाज़ नहीं करता। कभी-कभी, जगह पर अधिक अनुसंधान करना आवश्यक होगा।\nमैं पाठकों को सिद्धांत बिना बिगोट के इन पृष्ठों का पठन और विचार करने की सिफारिश करता हूं। यह एप्लिकेशन बेचने के लिए पेश किया गया है और लेखक द्वारा उचित माने गए किसी भी साधन के माध्यम से आगे की संचारण के लिए है। जो वित्तीय, कानूनी — और यात्रा मार्गदर्शन या शहर में प्रदान किए गए किसी भी प्रकार की सेवा में शामिल नहीं होगा। जो कुछ भी मामला हो सकता है जहां पेशेवर यात्रा मार्गदर्शक की आवश्यकता हो, उस स्थिति में इस क्षेत्र में एक पेशेवर की सेवाओं का उपयोग किया जाना चाहिए।\nसभी अधिकार सुरक्षित हैं। इस एप्लिकेशन का कोई भी हिस्सा किसी भी प्रारूप में लेखक की व्यक्तिगत लिखित अधिकार से बिना पुनः उत्पादित किए जा सकता है।\nहर एक तस्वीर का लाइसेंस Shutterstock.com से इस्तेमाल किया जाता है। यदि आप किसी तस्वीर के बारे में विशिष्ट जानकारी चाहते हैं, तो कृपया हमसे संपर्क करें। इस एप्लिकेशन द्वारा निर्धारित बाहर किसी भी परिस्थिति के अलावा कोई भी तस्वीर पुनः उत्पादित या उपयोग किया जा सकता है।\nसभी अधिकार सुरक्षित हैं। -लेखक / प्रकाशक से लिखित अनुमति के बिना इस एप्लिकेशन का कोई भी हिस्सा किसी भी रूप में या किसी भी इलेक्ट्रॉनिक या मैकेनिकल माध्यम द्वारा पुनः उत्पादित नहीं किया जा सकता है, सहित सूचना संग्रह और पुनः प्राप्ति प्रणालियों; प्रकाशक / प्रकाशक से लिखित अनुमति के बिना।",
          "PrivatePolicy": "गोपनीयता नीति"
        },
        "Spanish": {
          "text1": "Vamos a explorar",
          "text2": "Londres",
          "sidebartext1": "Mapa del metro",
          "sidebartext2": "Eventos",
          "sidebartext3": "Cosas para hacer",
          "sidebartext4": "Hoteles",
          "sidebartext5": "Clima",
          "sidebartext6": "Acerca de",
          "sidebartext7": "Contáctenos",
          "sidebartext8": "Instagram",
          "sidebartext9": "Facebook",
          "button1": "Mapa del metro sin conexión",
          "ContactText":
              "Contáctanos en un momento conveniente para ti y responderemos todas tus preguntas.",
          "ContactTile1": "Escríbenos",
          "Heading1": "Cosas para hacer",
          "Heading2": "Hoteles",
          "Heading3": "Clima",
          "Heading4": "Sobre nosotros",
          "Heading5": "Contáctenos",
          "Publish": "Nota del editor",
          "PublishText":
              "Esta aplicación ha sido escrita y diseñada para proporcionar información completa sobre este lugar. Al igual que con la publicación de la aplicación, no ignoro las limitaciones de la aplicación. En ocasiones, será necesario hacer más investigaciones sobre el lugar.\nRecomiendo que el lector ojeé y reflexione sobre estas páginas sin prejuicios. Esta aplicación se ha ofrecido a la venta y transmisión posterior a través de los medios que el autor considere apropiados y que no se dedicará a prestar orientación financiera, legal — y de viajes o cualquier otro tipo de servicio proporcionado en la ciudad. En cualquier caso que pueda surgir donde se requiera un guía de viajes profesional, entonces los servicios de un profesional en este campo deben ser enlistados.\nTodos los derechos reservados. NINGUNA PARTE de esta aplicación puede ser reproducida en cualquier formato sin la autorización expresa por escrito del autor.\nCada imagen se utiliza con licencia de Shutterstock.com. Si desea información específica sobre una imagen, póngase en contacto con nosotros. Ninguna de las imágenes puede ser reproducida o utilizada bajo ninguna circunstancia además de lo que pretende esta aplicación.\nTodos los derechos reservados. -Ninguna parte de esta aplicación puede ser reproducida en ninguna forma o por ningún medio electrónico o mecánico, incluyendo sistemas de almacenamiento y recuperación de información; sin permiso por escrito del Autor/Editor.",
          "PrivatePolicy": "Política de privacidad"
        },
        "Russian": {
          "text1": "Давайте исследовать",
          "text2": "Лондон",
          "sidebartext1": "Карта метро",
          "sidebartext2": "События",
          "sidebartext3": "Что делать",
          "sidebartext4": "Отели",
          "sidebartext5": "Погода",
          "sidebartext6": "О нас",
          "sidebartext7": "Свяжитесь с нами",
          "sidebartext8": "Инстаграм",
          "sidebartext9": "Facebook",
          "button1": "Офлайн карта метро",
          "ContactText":
              "Свяжитесь с нами в удобное для вас время, и мы ответим на все ваши вопросы.",
          "ContactTile1": "Напишите нам",
          "Heading1": "Что делать",
          "Heading2": "Отели",
          "Heading3": "Погода",
          "Heading4": "О нас",
          "Heading5": "Свяжитесь с нами",
          "Publish": "Примечание издателя",
          "PublishText":
              "Это приложение было написано и разработано для предоставления подробной информации об этом месте. Как и с публикацией приложения, я не игнорирую ограничения приложения. В некоторых случаях будет необходимо провести дополнительные исследования места.\nЯ рекомендую читателю ознакомиться и обдумать эти страницы без предвзятости. Это приложение было предложено к продаже и последующей передаче через те средства, которые автор считает подходящими, и не будет заниматься предоставлением финансовых, юридических — и путеводных или любых других видов услуг, предоставляемых в городе. В случае возникновения ситуации, когда требуется профессиональный путеводитель, следует воспользоваться услугами профессионала в этой области.\nВсе права защищены. НИ ОДНА ЧАСТЬ этого приложения не может быть воспроизведена в любом формате без явного письменного разрешения автора.\nКаждое изображение используется по лицензии от Shutterstock.com. Если вам нужна конкретная информация об изображении, пожалуйста, свяжитесь с нами. Ни одно изображение не может быть воспроизведено или использовано в любых обстоятельствах, кроме того, что предусмотрено этим приложением.\nВсе права защищены. -Никакая часть этого приложения не может быть воспроизведена в любой форме или любым электронным или механическим способом, включая системы хранения и извлечения информации; без письменного разрешения Автора/Издателя.",
          "PrivatePolicy": "Политика конфиденциальности"
        },
        "Turkish": {
          "text1": "Keşfetmeye Başlayalım",
          "text2": "Londra",
          "sidebartext1": "Metro Haritası",
          "sidebartext2": "Etkinlikler",
          "sidebartext3": "Yapılacak Şeyler",
          "sidebartext4": "Oteller",
          "sidebartext5": "Hava Durumu",
          "sidebartext6": "Hakkında",
          "sidebartext7": "Bize Ulaşın",
          "sidebartext8": "Instagram",
          "sidebartext9": "Facebook",
          "button1": "Çevrimdışı Metro Haritası",
          "ContactText":
              "Size uygun bir zamanda bizimle iletişime geçin ve tüm sorularınızı yanıtlayacağız.",
          "ContactTile1": "Bize yazın",
          "Heading1": "Yapılacak Şeyler",
          "Heading2": "Oteller",
          "Heading3": "Hava Durumu",
          "Heading4": "Hakkımızda",
          "Heading5": "Bize Ulaşın",
          "Publish": "Yayıncının Notu",
          "PublishText":
              "Bu uygulama, bu yere dair detaylı bilgi sağlamak amacıyla yazılmış ve tasarlanmıştır. Uygulamanın yayınlanmasıyla birlikte, uygulamanın sınırlamalarını göz ardı etmiyorum. Zaman zaman, yer hakkında daha fazla araştırma yapmak gerekebilir.\nOkuyucunun bu sayfaları önyargısız bir şekilde incelemesini ve üzerinde düşünmesini tavsiye ederim. Bu uygulama, satışa sunulmuş ve yazar tarafından uygun görülen herhangi bir aracılık yoluyla ileriye doğru iletilmiştir ve şehirde sunulan finansal, yasal — ve seyahat rehberliği veya başka herhangi bir hizmet sağlama gibi herhangi bir hizmette bulunmayacak.\nTecrübeli bir seyahat rehberinin gerektiği bir durumda, bu alanda bir profesyonelin hizmetlerinden yararlanılmalıdır.\nTüm hakları saklıdır. Bu uygulamanın HERHANGİ bir bölümü, yazarın açık yazılı izni olmadan hangi formatta olursa olsun yeniden üretilmez.\nHer bir resim, Shutterstock.com lisansı altında kullanılmıştır. Bir resim hakkında belirli bilgiye ihtiyacınız varsa, lütfen bizimle iletişime geçin. Resimlerin hiçbiri, bu uygulamanın amaçladığından başka hiçbir durumda yeniden üretilemez veya kullanılamaz.\nTüm hakları saklıdır. -Yazar/Yayıncıdan yazılı izin almadan, bilgi depolama ve geri alma sistemleri de dahil olmak üzere herhangi bir elektronik veya mekanik araçla bu uygulamanın herhangi bir bölümü, hiçbir formda çoğaltılamaz.",
          "PrivatePolicy": "Gizlilik Politikası"
        }
      };
}
