// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC50naRRb015gN3D-HB2nriZVH6Zk2Kx9E',
    appId: '1:59403745028:web:94d92d4a1961c7b76bc251',
    messagingSenderId: '59403745028',
    projectId: 'london-metro-map',
    authDomain: 'london-metro-map.firebaseapp.com',
    storageBucket: 'london-metro-map.appspot.com',
    measurementId: 'G-6TGDQBQ6HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUpK1995IgU34kIKwj5xE28rT5Jtc_2dw',
    appId: '1:59403745028:android:24d6a7de1eee22d76bc251',
    messagingSenderId: '59403745028',
    projectId: 'london-metro-map',
    storageBucket: 'london-metro-map.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCccExkPdyeF3LlZPO8UUA6EckQc-QULt4',
    appId: '1:59403745028:ios:7e24ed059fbe470e6bc251',
    messagingSenderId: '59403745028',
    projectId: 'london-metro-map',
    storageBucket: 'london-metro-map.appspot.com',
    iosBundleId: 'com.example.londonMetro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCccExkPdyeF3LlZPO8UUA6EckQc-QULt4',
    appId: '1:59403745028:ios:7e24ed059fbe470e6bc251',
    messagingSenderId: '59403745028',
    projectId: 'london-metro-map',
    storageBucket: 'london-metro-map.appspot.com',
    iosBundleId: 'com.example.londonMetro',
  );
}
