// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbp6wstSTFJFCjq5ABn7xDRYFbRhIDHCg',
    appId: '1:668814210878:web:2ba010ff6d405aa6e8de6f',
    messagingSenderId: '668814210878',
    projectId: 'world-metro-map',
    authDomain: 'world-metro-map.firebaseapp.com',
    storageBucket: 'world-metro-map.appspot.com',
    measurementId: 'G-9C4SGK8RP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEJP9Lr-hQyEWOisvkZVgN7bB24jXMCYM',
    appId: '1:668814210878:android:9821f7e86371a570e8de6f',
    messagingSenderId: '668814210878',
    projectId: 'world-metro-map',
    storageBucket: 'world-metro-map.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2l83hb7rZAsHG3GguKK5EcRGk4uLj1as',
    appId: '1:668814210878:ios:bc77e194f05901ebe8de6f',
    messagingSenderId: '668814210878',
    projectId: 'world-metro-map',
    storageBucket: 'world-metro-map.appspot.com',
    iosBundleId: 'com.example.worldMetro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2l83hb7rZAsHG3GguKK5EcRGk4uLj1as',
    appId: '1:668814210878:ios:bc77e194f05901ebe8de6f',
    messagingSenderId: '668814210878',
    projectId: 'world-metro-map',
    storageBucket: 'world-metro-map.appspot.com',
    iosBundleId: 'com.example.worldMetro',
  );
}
