// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNjAMT3eSWgbBGD2RsjUADf1TwIVJDYCw',
    appId: '1:338477616586:web:7fba02392018b3b5db1333',
    messagingSenderId: '338477616586',
    projectId: 'istanbul-metro-map-93ada',
    authDomain: 'istanbul-metro-map-93ada.firebaseapp.com',
    storageBucket: 'istanbul-metro-map-93ada.appspot.com',
    measurementId: 'G-HS715EXLJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbBY6b6LF-8eJZSl19QyJ_1wrSXIt9gKw',
    appId: '1:338477616586:android:82ad0f012f325634db1333',
    messagingSenderId: '338477616586',
    projectId: 'istanbul-metro-map-93ada',
    storageBucket: 'istanbul-metro-map-93ada.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPVKo_PUM6YcRieV_2CCRI5sBnKMtKAM8',
    appId: '1:338477616586:ios:6239c2c05eccc5e1db1333',
    messagingSenderId: '338477616586',
    projectId: 'istanbul-metro-map-93ada',
    storageBucket: 'istanbul-metro-map-93ada.appspot.com',
    iosBundleId: 'com.example.istanbulMetro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPVKo_PUM6YcRieV_2CCRI5sBnKMtKAM8',
    appId: '1:338477616586:ios:6239c2c05eccc5e1db1333',
    messagingSenderId: '338477616586',
    projectId: 'istanbul-metro-map-93ada',
    storageBucket: 'istanbul-metro-map-93ada.appspot.com',
    iosBundleId: 'com.example.istanbulMetro',
  );
}
